name: Apple
env:
    NWS_AGENT_CONTACT: ${{ secrets.NWS_AGENT_CONTACT }}
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  macos:
    runs-on: macos-latest
    steps:
    - uses: maxim-lobanov/setup-xcode@v1.1
      with:
        xcode-version: 12
    - uses: actions/checkout@v2
    - uses: actions/cache@v2
      with:
        path: .build
        key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-spm-
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
